### ISSUE TITLE
Plugin's css classes won't working

### ISSUE THREAD

**Issue by CodeLit** [Booster1212/plugin-notifications#1]
When I'm trying to put the plugin in, the notification styles are disappear. I see in the code there are uses of classes `flex items-center w-full` etc. I understand that under the hood `tailwindcss` is used, which is not loaded with the plugin. Please, fix.

![image](https://github.com/Booster1212/plugin-notifications/assets/37398131/5b97a751-50ea-4d11-9a5b-920f20da3b12)

**Comment by Booster1212** [comment]
Only works on Athena v6.0.0 which is a broken development branch currently.

Sorry.
